setup.cfg
This is so "yum install puppetboard" also pulls in all the required python module RPMs automatically.
=> Add requires section to setup.cfg

README.rst
The example was missing the protocol part of the backend server URL
('http://'). This causes nginx to complain of a "malformed URL".
=> Fix proxy_pass line in nginx+gunicorn example.

puppetboard/app.py
[puppet-hipchat](https://github.com/jamtur01/puppet-hipchat) has this very helpful feature where the puppet runs that are logged in the chat are posted with a link to the report.
Unfortunately, for now only the '/latest' report can be linked as the report hash is not available in the puppet report format.
I thought the easiest way to change this is to optionally accept the configuration_version as the `<report_id>`. It's a tiny change really, but it would help solve this problem:
https://github.com/jamtur01/puppet-hipchat/pull/23#discussion-diff-10535251
We'll then end up with this:
=> Accept the configuration_version as alternative in the report view.

puppetboard/static/coffeescript/tables.coffee, puppetboard/static/js/tables.js
Hello, this pull request addresses issue #6 and also incorporates some touch-ups to the syntax of the coffee file to be consistent throughout (2-space indentation primarily).
This may cause a little trouble when merged with my other pull request #137, happy to help if it causes any drama, you'll need to update the dashboard tablesorter to use my new `timestamp` sorter for the report column which I added :smile: 
Cheers
Fotis
=> Repaired sorting of date columns

puppetboard/templates/_macros.html
97bbe96 renamed the keyword arguments for report(node_name, report_id) but _macros.html wasn't updated
=> Patch _macros.html for the latest cleanups

puppetboard/app.py, puppetboard/default_settings.py, puppetboard/static/js/tables.js, puppetboard/templates/inventory.html, puppetboard/templates/layout.html
I used to update my inventory list automatically via other means, but since I installed PuppetBoard a couple of days ago, I thought it was a good fit. PuppetBoard provides great visibility to the status of the Puppet infrastructure, but I also needed a custom single view of my nodes along with a set of facts. The inventory page usability can be greatly enhanced using custom facts. Some of the custom facts I use with it are "reboot_required", "updates_available", "ufw_active", etc.
Synopsis:
Added inventory page showing a table similar to the "Nodes" one, but containing any customizable set of facts. A setting INVENTORY_FACTS has been added. It controls the list of facts to be displayed along with a description for the header of the table. I would've added a setting to hide the tab …
=> Added inventory page along with a navbar link.

puppetboard/app.py, puppetboard/default_settings.py, puppetboard/static/coffeescript/tables.coffee, puppetboard/static/js/tables.js, puppetboard/templates/catalog.html, puppetboard/templates/nodes.html
This makes use of the available catalog endpoints in pypuppetdb and PuppetDB
and displays to administrators the last compiled catalog for a node,
if the variable ENABLE_CATALOG is True (defaults to False)
This is a re-work of https://github.com/puppet-community/puppetboard/pull/93 and https://github.com/puppet-community/puppetboard/pull/115
=> puppetboard: Adding Catalog Viewer

puppetboard/app.py
Instead of querying the ```/facts``` endpoint in PuppetDB for every fact that it knows about only
query it for the names that we want. The result is a
much smaller result set that is more noticeable on environments with
large numbers of nodes and/or facts.
On one environment with > 2500 fact-names and 35 nodes a curl test
to the facts endpoint without any query string returned in ~3.5 seconds.
Ran another curl test to the facts endpoint with the query string that
the code in this commit creates, the command finished in ~0.040 seconds.
This is an update for the functionality that was introduced in https://github.com/puppet-community/puppetboard/pull/135
=> puppetboard/app.py: Optimizing the inventory page

CHANGELOG.rst, puppetboard/templates/layout.html, setup.py
In preparation for the release of 0.1.0, with PuppetDB 3.x support, bumping the version from 0.0.4 to 0.0.5.
The most significant change is the setup now requires pypuppetdb < 0.2.0 instead of >= 0.1.0
=> puppetboard: Version bump to 0.0.5

puppetboard/templates/query.html
The query field `name` was replaced with `certname`. https://docs.puppetlabs.com/puppetdb/3.1/api/query/v4/nodes.html#query-fields
`["=", "name", "hostname"]` fails where as `["=", "certname", "hostname"]` works as expected
=> update query example to use certname

puppetboard/static/css/puppetboard.css, puppetboard/templates/index.html, puppetboard/templates/nodes.html
"Skips" were highlighted with orange on one page and yellow on another. This change makes them consistent, and switches the color to "black" for accessibility reasons. (The contrast between the shades of orange and red used for skips and errors was *very* low. Indistinguishable on some screens.)
=> Make "skips" color consistent

puppetboard/app.py, requirements.txt, setup.py
This PR adapts puppetboard to work with https://github.com/puppet-community/pypuppetdb/pull/58
All the features seemed to work fine with that.
=> Make Puppetboard work with the PuppetDB V4 api

puppetboard/app.py, puppetboard/forms.py, puppetboard/templates/catalog.html, puppetboard/templates/catalog_compare.html, puppetboard/templates/catalogs.html, puppetboard/templates/layout.html
A new endpoint in the header, Catalogs, takes the user to a page with a node
table similar to that in the nodes page. This table shows the node with a
link to the node page, the catalog timestamp with a link to the catalog
page and a small form with a select field to be used to compare the
catalog of this row's node with that of another node.
This comes after a discussion with other project maintainers about adding functionality to, in addition to making a Catalogs endpoint, compare the catalogs between 2 nodes. This page's URL looks similar with github's commit/branch compare page with the value /catalogs/compare/<compare>...<against>
This has been tested against a PuppetDB 3.x system with 2 nodes but it uses the query functionality of the catalogs endpoint that is available in PuppetDB …
=> puppetboard: Adding a more intuitive catalog view

README.rst, puppetboard/templates/layout.html
This bar reduces the available vertical space and other maintainers feel
it better to remove it than to modify it.
Also reducing the specific mention of @daenney from README.rst since he
has steped down as main project maintainer.
=> puppetboard/templates/layout: Removing the footer bar

puppetboard/templates/reports.html
This fixes https://github.com/puppet-community/puppetboard/issues/181
=> puppetboard/templates/reports: Passing current_env to the reports_table macro

puppetboard/templates/layout.html
the version of puppetboard was updated to 0.1.1 but the version number in this layout file was still 0.1.0.
=> version number updated in templates/layout.html

puppetboard/app.py, puppetboard/default_settings.py, puppetboard/templates/index.html
Add an auto refresh to the index page.
=> Add auto-refresh on index page

CHANGELOG.rst, puppetboard/app.py
Moving the global environment list from a global context to a functional
context because octomike reported that the environment list in his environment
was not being refreshed. Fixes https://github.com/puppet-community/puppetboard/issues/186
Adding CHANGELOG entries for 0.1.1 and this new change.
=> puppetboard: Reloading the available environments on every page load.

puppetboard/templates/catalog_compare.html
Fixed https://github.com/puppet-community/puppetboard/issues/193
Fixed Semantic UI tables set a fixed position on the applied tables
that do not affect the alignment with narrow browser windows. Downside
of this approach is that users will have to scroll horizontally to view
the entire catalog comparison.
=> templates/catalog_compare: Switching from basic tables to fixed tables

puppetboard/app.py, puppetboard/templates/catalog.html, puppetboard/templates/index.html, puppetboard/templates/nodes.html, setup.py
Showing the Code ID field in the catalogs page. This is currently
unused in PuppetDB as of 3.2.2 but may be useful when it will be used
If available, using the latest_report_hash field of the node object
in the index and nodes templates for the link to the latest report
available for the node.
Updating the report_latest function in app.py to query the nodes
endpoint and redirecting using the latest_report_hash field if available.
If not query the reports endpoint for the node's latest report.
=> Using new Node and Catalog fields available in pypuppetdb 0.2.1

puppetboard/app.py
Fixes https://github.com/voxpupuli/puppetboard/issues/209
The event_count queries for the reports in the reports() and reports_node()
functions were always filtering on environments, even if all environments, *,
were selected. This update removes the environment clause from the query
string if 'All Environments' are selected
=> puppetboard/app.py: Don't filter on environments if all are selected

puppetboard/static/css/puppetboard.css, puppetboard/templates/_macros.html, puppetboard/templates/index.html, puppetboard/templates/report.html
Other tools such as Dashboard and Foreman use red for failed, green for unchanged and blue for changed resources. This PR adjusts the colors used so that Puppetboard behaves like the rest of these interfaces.
Result:
=> Use more standard colors for Puppet run states

puppetboard/app.py
I really did not want to resort to this but I could not find any answers
from previously asked questions on the subject. The template is properly
creating the csrf_token hidden field which is being submitted to the server,
but I could not figure out why it was not using it it.
This fixes https://github.com/voxpupuli/puppetboard/issues/198
This will not be permanent, will have to look into upgrading the flask-wtf
and WTForms packages to the latest versions.
=> puppetboard/app: Disabling CSRF protection globally.

puppetboard/app.py
This fixes https://github.com/voxpupuli/puppetboard/issues/218
Adding environment filters to only report then number of managed nodes
and resources that are present in the current environment. Still using
the same metrics endpoint information for all environments.
=> puppetboard/app: Enabling environment filtering on overview metrics

README.rst
Added an examples section to the readme to list examples/demo's to show off the puppetboard functionality.
=> Examples add to the readme

puppetboard/app.py
This fixes https://github.com/voxpupuli/puppetboard/issues/220
If the PuppetDB instance is not being properly cleaned up, i.e. deactivated or
expired nodes leave environment(s) empty, the queries try to determine the average
resource count per node by dividing the resources in the current environment by
the number of nodes in the environment. This patch protects against such an event.
=> puppetboard/app.py: Protecting against ZeroDivisionErrors

requirements.txt
'PROTOCOL_SSLv3'"
Running debian 8.2 (jessie) I experience the following:
```
Traceback (most recent call last):
File "dev.py", line 11, in <module>
from puppetboard.app import app
File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 19, in <module>
from pypuppetdb import connect
File "/srv/puppetboard/virtenv-puppetboard/local/lib/python2.7/site-packages/pypuppetdb/__init__.py", line 61, in <module>
from pypuppetdb.api import BaseAPI
File "/srv/puppetboard/virtenv-puppetboard/local/lib/python2.7/site-packages/pypuppetdb/api/__init__.py", line 7, in <module>
import requests
File "/srv/puppetboard/virtenv-puppetboard/local/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
from .packages.urllib3.contrib import pyopenssl
File …
```
=> Fix error "AttributeError: 'module' object has no attribute

puppetboard/utils.py
This fixes https://github.com/voxpupuli/puppetboard/issues/230
If there are any connection issues between PuppetBoard and the PuppetDB
instance there wasn't any obvious evidence in log files. This additional
logging added to utils.py logs errors whenever there is an HTTPError,
ConnectionError or EmptyResponseError in get_or_abort.
=> utils.py: Adding logging to :func:`puppetboard.utils.get_or_abort`

puppetboard/templates/_macros.html
This fixes https://github.com/voxpupuli/puppetboard/issues/229
This menu provides a very user friendly interface for rendering the pagination
section, which is available in version 2.1.8. Updating the render_pagination
macro use the new HTML classes.
=> puppetboard/templates/_macros.html: Using the Semantic UI Pagination Menu

puppetboard/app.py, puppetboard/templates/_macros.html, puppetboard/templates/index.html, puppetboard/templates/nodes.html
This fixes https://github.com/voxpupuli/puppetboard/issues/234
The report_latest() function was effectively deprecated when PuppetDB
introduced the latest_report_hash field in the Nodes endpoint response
format in version 3.2. With the breaking changes to PuppetDB 4.0.0
support this function can be safely removed.
=> puppetboard/app.py: Removing :func:`puppetboard/report_latest`

puppetboard/app.py, puppetboard/default_settings.py
This allows to filter out nodes in the overview by passing queries to the PuppetDB in the `OVERVIEW_FILTER` configuration parameter.
For example, if I don't want to see the machines whose certname matches `wrk`, I can use:
```
OVERVIEW_FILTER = '["not", ["~", "certname", "wrk"]]'
```
=> Add OVERVIEW_FILTER

puppetboard/templates/_macros.html
I (and my colleagues) believe this sort order makes more sense. By lumping the lowest ranked results together instead of potentially the largest. (As an example we have 18 different CPUs and the other category accounted for 67% using the default sort or 1.2% when reversed.
=> reverse sort order to lump minorities in 'other' instead of majorities

puppetboard/app.py, puppetboard/templates/_macros.html, puppetboard/templates/layout.html, puppetboard/templates/node.html, puppetboard/templates/reports.html
This resolves #202 
The fix for this issue has to come in 3 parts:
1. Replace the reports table status information originally populated by querying the event-counts endpoint with querying the current report's events. This was functionally nor required but this reduces the risk of loosing environment filters on the event-count queries.
2. Replace the `url_for_pagination()` and `url_for_environments()` function with a new `url_for_field()`. This new function updates a single request argument with a new value and returns the generated URL for the request endpoint.
3. Add a dropdown menu on the `reports()` and `reports_node()` pages to change the limit of the number of reports displayed on the page.
=> More Easily View All Reports

puppetboard/utils.py
If `xrange()` is not defined, alias it to `range()`.
=> puppetboard/utils.py: fix Python3 compatibility

puppetboard/utils.py
Was having a permissions error when executing under a container.  This was throwing an exception and ran into 'e' not being defined.
=> Fix exceptions to assign the exception to a variable

README.rst
With the IP address of the gunicorn server set in proxy_pass, the configuration example doesn't need to declare an upstream server.
=> Removing redudant declaration of upstream in Nginx example

README.rst, puppetboard/app.py, requirements.txt, setup.py
This fixes #243 
Upgrading the following packages to the respected versions:
WTForms==2.1
Flask-WTF==0.12
Werkzeug==0.11.0
Passing newly required metadata to the QueryForm constructor in puppetboard/app.py
Apache >= 2.4 with mod_wsgi experienced a major issue where it would re-generate
the app's secret key on each request. The fix for this turned out to be placing
a permanent statis 'secret_key' value in the wsgi.py. Adding a block in README.rst
on how to implement the user's own secret_key
=> PuppetBoard: Upgrading WTForms to latest version and restoring CSRF Protection

puppetboard/app.py, puppetboard/templates/metrics.html
This fixes #258
URL quoting is now done in pypuppetdb >= 0.2.3 which contributed to the
metric URL being double-quoted by the time it reached PuppetDB, which
responds with a 404. Instead using the plain-text name to build the
link to metric()
=> puppetboard/app.py: Using the plain-text metric name in metrics()

README.rst
Github wasn't showing the new readme blocks because they were encoded
code_block instead of the correct code-block.
=> README.rst: Fixing code-block strings.

puppetboard/static/js/jquery.min.map, puppetboard/templates/radiator.html
Radiatorview was using the wrong link for jquery.js. Which was found by @amuametov
Adding in the OFFLINE setting which is used to determine local or remote JS.
Removing symlink of jquery.min.map, which is not referenced anywhere.
Closes #269 and #270
=> Update radiator view

README.rst
coveralls.io badge.
Is there better way to reference the badge?  so that the README.rst knows who's linking to it?
=> Add coveralls.io badge

README.rst
* Require links to be on newline
Before:
After:
Helping hand from http://stackoverflow.com/questions/14087784/linked-image-in-restructuredtext
=> Fix rst syntax for badges

.travis.yml
Looks like things run well under python 3.5 on our Ubuntu 16.04 install with PuppetDB 4.x. Run tests on python 3.5 to make sure things do not break.
=> Travis: run tests under python 3.5

README.rst, puppetboard/app.py, puppetboard/templates/nodes.html, puppetboard/templates/reports.html
This resolves #264
On the Nodes and Reports tabs when the user adds a status query string
argument additional query clauses are generated based on its value.
Can be one of failed, changed, unchanged, noop or unreported (for Nodes
only)
No query clause is generated for noop on the Nodes tab. The query field
latest_report_noop was added in PuppetDB 4.1 and we do not want to break
compatability between minor or bug-fix versions.
=> puppetboard/app.py: Enhancing queries for Node and Report states

puppetboard/app.py, puppetboard/templates/inventory.html
This resolves #275
This update eliminates one iteration over the resulting inventory facts
that generates a multidimensional dictionary keyed by the node's certname
to another dictionary of key-value pairs of the fact name and fact value.
=> puppetboard/app.py: Simplifying the Inventory Code

puppetboard/templates/_macros.html, puppetboard/templates/catalog.html, puppetboard/templates/catalogs.html, puppetboard/templates/index.html, puppetboard/templates/node.html, puppetboard/templates/nodes.html, puppetboard/templates/report.html
Certain column headers were referring to a node's certname as its
hostname. This commit corrects that by renaming the column headers.
If the intention was to display the hostnames instead of the certnames then please close this PR and I'll create a new one.
=> Change hostname to certname where applicable

puppetboard/app.py
This resolves #276
Current behaviour of the Facts page would query the fact_names endpoint
regardless of environment. This update would query the Facts endpoint,
extracting each unique fact name known to the environment.
=> puppetboard/app.py: Adding an environment filter for displaying Fact names

puppetboard/templates/metrics.html
This resolves #297
Adding a search bar to the Metrics page to allow the user to filter the list
items to only show what the user wants.
=> puppetboard/templates/metrics.html: Added searchability to the Metrics list

puppetboard/app.py, requirements-test.txt, setup.cfg, test/test_utils.py
Increasing coverage on utils.  Pinned py.test and adding unittest2 for python 2.6 support.
Fixing issue #299 as well, which is covered in a unittest.
=> Adding unittests

puppetboard/static/css/radiator.css
When using more than 1000 nodes>
The count values get clipped on all rows
But setting to 100% width produces the following:
=> radiator column width to percent

puppetboard/docker_settings.py, test/test_docker_settings.py
This allows to plug and play a PuppetDB container (or use extra host)
=> Use puppetdb as PUPPETDB_HOST on Docker

puppetboard/app.py
In radiator, when an environment as no nodes, num_nodes is null. This patch catch the divisions by zero and set the results to 0 in this case
=> catch a division by zero in radiator while environment has no nodes

setup.py
During setup (apache + wsgi), I got errors about templates ("File not found").
Found this parameter to solve it. It prevents pip/easy_install to zip python module (used by egg installation mode) in installation directory.
=> Setup.py : zip_safe to permit static serve

puppetboard/app.py, puppetboard/utils.py, test/test_app.py, test/test_utils.py
Mbeans use type=default in puppetdb 3x, type was removed in 4x.
I would like to use the new testing framework in #326 
Fixes #330
=> Support for PuppetDB 3.x on all environments

.travis.yml, dev.py, puppetboard/app.py, puppetboard/templates/reports.json.tpl, scripts/unpin.py
Adding "Unpinned" upgrade checks on packages that puppetboard depends on.  These unpinned checks are allowed to fail, but will identify when a new release of a package will break puppetboard.
Adding fixes for newer Flask, Jinja2 and pep8 issues.  Fixing #345
=> Support for latest version

README.rst
from Jasper Lievisse Adriaanse to Sebastian Reitenbach
so update the README.rts accordingly.
=> Puppet related ports/package maintenance on OpenBSD was taken over

puppetboard/app.py, puppetboard/templates/catalogs.html, puppetboard/templates/catalogs.json.tpl, test/test_app.py
Revamped in a two step selection.
=> Revamp catalog page with paging

.travis.yml, setup.py
Cannot install the least version of Werkzeug, this causes issues with the abort handling that was introduced and then removed.
This is in preparation of a release 0.2.2
=> Bounded the latest version of Werkzeug

puppetboard/app.py, puppetboard/templates/report.html, requirements.txt
This allows to use markdown in `config_version`. I use this to make clickable links, e.g. if the config_version is:
```
[fix foo.wrk.lsn to hello.wrk.lsn](https://git.example.net/example/puppetmaster/commit/b4a9a6aaa606846ddkufk10e8ebc6feeb6358e55)
```
it will render it as a link with the commit message as text, and linking to the commit page.
=> Commonmark version

puppetboard/static/js/dailychart.js
When puppetboard is being run from a directory instead of the root of the domain, the daily chart will not work as it tries to load the data from the root. This change makes it load the data from the current working URL, instead of forcing root.
=> Fix dailychart.js when using non-root location

hooks/pre_build
Using new cloud.docker to build containers.  During the prebuild set the version that was checked out and set the __version__ value.
=> Adding Docker puppet version tagging

puppetboard/app.py, puppetboard/default_settings.py, puppetboard/docker_settings.py, puppetboard/static/css/puppetboard.css, puppetboard/templates/_macros.html, puppetboard/templates/reports.json.tpl, test/test_docker_settings.py
Sum up 'noop' and 'skipped' resources from reports into displayed "skips" value. Particularly relevant when doing 'noop' runs on nodes in order to identify how far the node is from baseline.
'noop' resources may also be explicitly declared in catalogs (even in normal run). In this case, we are losing a bit of information. But, I don't know what is the typical use case of noop resource. This use case may match our interface behavior.
=> Add total and noop boxes on reports page.

puppetboard/app.py, puppetboard/templates/inventory.html, puppetboard/templates/inventory.json.tpl, test/test_app.py
Same one here about inventory page.
Unfortunately, ordering is not working on facts value (nor on /facts, nor on /fact-contents, despite last one should support it according to puppetdb documentation).
Workaround is to load the overall data in one call with "serverSide" set to off in datatables. Paging/Sorting is still working on client side.
Load times (on my test platform @6k nodes)
* previous page (4s load, 4s DOM treatment, 1s sorting)
* now (<500ms load, 2,5s json query, <100ms DOM with 100 lines, <100ms sorting)
=> Inventory page revamp with paging

puppetboard/app.py, puppetboard/templates/_macros.html, puppetboard/templates/fact.html
Encode paths properly so that they do not cause issues when trying to pass them in as fact search paths.
When getting a 404 or an error from the puppet board Ajax call allow datable to reset and return and error that shows no data and hide the processing box.
Fix #385.
=> Handle attribute error on path.

puppetboard/templates/index.html, puppetboard/templates/nodes.html
Related to #399
This change makes sorting by date on the nodes page work.
I noticed the date class seems to trigger the code on line 13 in `Puppetboard / puppetboard / static / js / tables.js`. But other pages, for example Catalogs, have dates that don't use the `.date` class and work.
So I removed the date class and it seems to fix the issue.
I'm wondering if this tables.js code for dates is being used elsewhere, if so is it working, if not should it be removed?
=> Remove date classes from nodes page

hooks/pre_build
to get the proper version from GitHub releases.
Only use git describe when docker builds master
use the tag name which is stored in the environment
variable SOURCE_BRANCH.
See:
https://docs.docker.com/docker-cloud/builds/advanced/#override-build-test-or-push-commands
=> Docker build needs to use light weight tags

puppetboard/static/js/tables.js, puppetboard/templates/index.html, puppetboard/templates/nodes.html
This is a follow up to #400 
I'm removing this code because I can't find it referenced anywhere other than the places I removed it from.
I realize this pull request doesn't add any functionality, but if someone adds a class of date to a `th` element this change will stop the functionality from breaking.
=> Fix sort by date on nodes and index page

puppetboard/utils.py
formatvalue fails for list of dicts with:
> TypeError: sequence item 0: expected string or Unicode, dict found
example: `formatvalue([{}])`
=> Fix formatvalue for list of dicts

puppetboard/static/css/puppetboard.css
This pull request helps with a layout issue I pointed out in #404. The Certname column is sometimes too long which makes the buttons display not as intended. 
In particular I found this helps on screens 1200px-1500px when cert-names are long.
=> Make 320px the max width for columns #404

puppetboard/app.py
This fixes https://github.com/voxpupuli/puppetboard/issues/437.
Based on the feedback on the issue I realized this only triggers when * environment is selected.
The error can be easily simulated with curl. This works `curl http://localhost:5000/production/fact/kernel/Linux/json` but this doesn't `http://localhost:5000/fact/kernel/Linux/json`.
The url without `<env>` returns this error:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb) …
```
=> If query is None don't perform add on it.

README.rst
True or False are expected (python booleans start with capital letters)
=> Fix documentation error regarding ENABLE_CATALOG

puppetboard/app.py, test/test_app.py
The endpoint /status can be used to determine if puppetboard is running or not.
Reason for needing an endpoint like this is because if the puppetdb has no
data yet (due to a fresh install for example), it will return a 404 on all pages.
This will throw off health checks for example docker or the AWS ALB.
The health check endpoint can later be expanded by puppetdb health as soon
as this functionality has been merged in the pypuppetdb module.
=> Adding basic health check endpoint

puppetboard/templates/_macros.html
Line breaks were added allowing see the facts in a structured way, e.g. for disks:
=> View of structured facts

Dockerfile, README.md
This change makes it a bit easier to deploy Docker images of Puppetboard without having to run the service on its own subdomain.
=> Add support for URL prefixes to Docker image

README.md
Simply update the README to state that Puppetboard works with PuppetDB 6 too.
=> Now tested with PuppetDB 6.x

.travis.yml, MANIFEST.in, puppetboard/utils.py, tox.ini
=> Fix failures on python3.7

README.md, puppetboard/app.py, puppetboard/default_settings.py, puppetboard/docker_settings.py, puppetboard/forms.py
Allow to configure which PuppetDB endpoints are allowed in the `/query`
page, adding the `ENABLED_QUERY_ENDPOINTS` configuration variable, that
if set restricts the allowed endpoints to query. If not set the previous
behaviour is kept, allowing all PuppetDB endpoints to be queried, if the
`ENABLE_QUERY` configuration is `True`.
Closes: #475
=> Allow to configure enabled query endpoints

Dockerfile
Since Python 2.x [is getting deprecated as of January 2020](https://pythonclock.org/), shouldn't we move to 3.6 for the supplied Dockerfile?
=> Move to Python 3.6 for Docker

puppetboard/templates/index.html, puppetboard/templates/layout.html
Removing extra links reported in #406 
Even with this change there seems to be 2 of both `d3.js` and `c3.js` on index.
=> remove duplicate c3.js/d3.js links

puppetboard/templates/layout.html
Fixes #519.  The c3.min.js and d3.min.js files are needed for graphs to work.
=> Revert "remove duplicate c3.js/d3.js links"

requirements.txt
Updating version of pypuppetdb to avoid missing requirements-test.txt issue present in versions 1.0.0 and 1.1.0.
This change is required to fix deployment issues with the current puppet-puppetboard module. It's a precursor a new release of the puppetboard module.
=> Updating pypuppetdb dependency to 1.2.0

.travis.yml, README.md, setup.py
Python 2.7 is deprecated in 2 months from now, so it's no longer necessary to support it for next release.
Python 3.8 is released, I think it's good to add it and drop Python 3.5.
=> Dropping support for python2.7 and python3.5 and adding python3.8

puppetboard/app.py, puppetboard/forms.py, pytest.ini, requirements-test.txt, test/test_app.py
Upgrade to latest versions of packages for tests with all necessary changes.
Adding also ignore for DeprecationWarning, since third party packages like requests show some warnings, which can't be affected from this project perspective.
=> Upgrade of tests requirements + resolving current deprecation warnings

puppetboard/app.py
Fixes #496
Because of https://tickets.puppetlabs.com/browse/PUP-9290 if someone
is using `puppet facts upload` their nodes have facts_environment set
always to "production". This breaks filtering in Puppetboard.
But it's both safe and beneficial to just ignore facts_environment
and depend only on catalog_environment to filter nodes by environment
because if a node is in env X then it mean that it has catalog_environment
set to X.
=> Ignore facts environment for compatibility and performance

puppetboard/app.py
This is a follow-up to #480, I cherry-picked the author's commit on top of master to prove that the test suite pass with these changes (except the Allowed failure that already fails with master).
Feel free to merge this PR or the original one; and close the other one at your convenience
Fixes #480
=> CommonMark >= 0.8.x preparation (rebased)

Dockerfile, pytest.ini, requirements-docker.txt, requirements-test.txt, setup.cfg
Gunicorn 20.0.0 is released so we can finally update Dockerfile to use Python3.8.
Additionally fixing coveralls not running and moving whole config for pytests to single file.
=> Update docker and fix coveralls not running.

puppetboard/templates/_macros.html
This prevents a type error for fact values in the inventory page that are numeric.  Some of our custom facts simply return a numeric count which causes the replace function to fail unless it's cast as a string.
=> Cast inventory data toString.

requirements.txt
This module is NOT compatible with Python 3.x The latest versions of PyPuppetDB (>2.x) are Python 3 only. 
Until PuppetBoard is updated to use Python 3 please change this back to ensure the module works. This change was obviously not correctly tested as it breaks Puppet board.
=> Fixing the requirements.txt as it's breaking Puppetboard.

CHANGELOG.md, puppetboard/app.py, requirements.txt, test/test_app.py
Tried using the latest version of `puppetboard` against the recently released PuppetDB 6.9.1 and ran into several problems related to them disabling the metrics/v1 endpoint (https://puppet.com/security/cve/CVE-2020-7943/) along with the bug fixes for metrics/v2 that were recently merged.
**Fixes**
- In Metrics v2 the `avg-resources-per-node` metric now returns a string in the format `1234/11` (`<total_resources>/<num_nodes>`). This displayed funny on the UI and was not consistent with previous behavior. To fix this i reverted back to computing the average resources per node as we were doing with metrics v1.
- In Metrics v2 the way you list all available metrics as done in the Metrics page changed. This page failed to load on the latest version. To support these changes i needed to update …
=> Fixed bugs in metrics v2 usage

puppetboard/app.py, test/test_app.py
Puppet Server releases done on 10 March 2020 forcefully disabled the metrics v1 endpoints. The appropriate change was made for Puppet Server 6.9.1 support, however Puppet Server 5.3.12 also needs the same treatment.
Although everyone is urged to upgrade when possible, in case someone wants to use Puppetboard and has not upgraded yet, we should support them, as the ['Puppet packages and versions'](https://puppet.com/docs/puppet/latest/about_agent.html#puppet-releases-and-lifecycle) docs page currently states that Puppet 5.5.x (Puppet Server 5.3.x) is expected to become EOL in November 2020.
Ref: #553, #555
=> Adjust metrics API for Puppet Server 5.3.x

.travis.yml, README.md, setup.py
This PR reverts [some off] #531 to support for python3.5 back to the test matrix.
closes #551
=> python3.5 (#551): add python 3.5 back to the test matrix

puppetboard/static/js/dailychart.js
provide relative path to daily_reports_chart.json on 'Overview' page
and absolute path on node page, since node page url is dynamic
Currently charts are broken, in case dashboard is not located in the root of the web site
=> fix path to daily_reports_chart.json

puppetboard/app.py, test/test_app.py
Puppet is now forcing the v2 metrics endpoint in PuppetDB 5.2.13.
=> Puppet DB 5.2.13 requires v2 metrics

requirements-test.txt
Travis's default python archive for python < 3.8 includes pytest 4.1, which does not match the requirements of the latest pytest-cov (v2.8.1). This has caused recent CI builds (#575, #576) to fail.
=> Fix CI builds by requiring pytest >= 4.6

puppetboard/templates/report.html
Currently puppetboard shows multiline messages (code diffs) on a single line as a part of the report, which makes it very difficult to read changed lines from the diff. This PR makes browsers preserve newlines in messages.
This pull request fills the same purpose as #408 but it doesn't decrease test coverage. It also makes diffs show up as monospace, which makes code changes easier to read.
=> Surround multiline messages with <pre> in reports

puppetboard/static/js/tables.js
An ascending sort order is always triggered when then target index is different
from the tablesort index. This was always true on a page (re)load, because
index is initialized with null.  By setting the instance' index to the
default-sort column index we assure that the direction parameter to sort() is
used.
See https://github.com/kylefox/jquery-tablesort/blob/master/jquery.tablesort.js#L42
=> Fix: default table sort was always ascending

README.md
Or do you prefer another background color for the Vox badge?
#8ac9ff: ![8ac9ff](https://img.shields.io/badge/by-Vox%20Pupuli%20%F0%9F%A6%8A-8ac9ff.svg)
#3f51b5: ![3f51b5](https://img.shields.io/badge/by-Vox%20Pupuli%20%F0%9F%A6%8A-3f51b5.svg)
Or even split:
=> Improve README badges

puppetboard/docker_settings.py
Add helper function `coerce_bool` to settings file to make it easier to
convert boolean-like values to a boolean.
=> Add WITH_EVENT_NUMBERS to docker_settings

.travis.yml, README.md, setup.py
The support of Python 3.5 ended at September 2020, so we should drop it from the test matrix
=> Remove Python 3.5 support

puppetboard/app.py, puppetboard/utils.py, test/test_utils.py
A PuppetDB Query with a Boolean Parameter must not be in quotes. This PR fix this issue and resolves #583
=> Convert Boolean Parameters to boolean for puppetdb query

.travis.yml
Move from Ubuntu Xenial 18.04 to Ubuntu Focal 20.04
=> travis: Test on Ubuntu 20.04 Focal instead of Xenial

puppetboard/templates/index.html, puppetboard/templates/layout.html, puppetboard/templates/node.html
Make the Puppetboard load slightly faster thanks to using cdnjs more/better:
* Get JavaScripts for Semantic-UI, c3 and d3 also from jscdn, like we already did for their CSS files,
* Update the existing links to the jscdn resources to the form suggested now by that service itself,
* Replace same-protocol (`//`) with the explicit HTTPS (`https://`) as jscdn redirects HTTP requests to HTTPS anyway,
...and cleanup unnecessary duplicate references to c3 and d3 resources.
=> Use cdnjs more/better

puppetboard/templates/radiator.html
This fixes the links to jquery 3.5.1
See also https://github.com/voxpupuli/puppetboard/pull/592 and https://github.com/voxpupuli/puppetboard/commit/558597c74d16e4cde32c8dcb5b01dee9fe2b1c36
=> Fix auto-resize in radiator view

README.md
as the officially recommended one.
Also simplify and clean up installation
instructions. Reformat all code fragments
to a more standard Markdown.
=> Switch to the new GHCR Docker image

puppetboard/app.py, test/test_app.py
Grouping facts by first letter is inefficient when a lot of facts begin
with some specific letters.  E.g. with multiple network interfaces.
Before:
After:
=> Improve facts columns balancing

.github/workflows/tests.yml, README.md, requirements.txt, setup.py, tox.ini
Pypuppetdb 2.4.0.rc1 is a pretty big new release. It contains some big refactoring and reorganization of the code. It should not break backward compatibility but with such amount of changes it needs more testing before a final release. See https://github.com/voxpupuli/pypuppetdb/pull/201 for more info.
Therefore let's test it - by the volunteers only, of course - in a pre-release of Puppeboard. See #620.
=> Pypuppetdb 2.4.0 & Python 3.9

.github/workflows/tests.yml, CHANGELOG.md, README.md, puppetboard/version.py, requirements.txt, setup.py, tox.ini
This pre-release is created mostly for people who will want to test the RC1 of pypyppetdb 2.4.0.
See #619 for more info.
=> Release 3.1.0.rc1

README.md
PupeptBoard is available as a package on FreeBSD.  Support for managing
PupeptBoard using system packages is WIP in puppet-puppetboard.
=> Enumerate FreeBSD package

settings.py.sample
This file is mostly useful when packaging PuppetBoard and providing a
sample configuration file with pointers to the documentation and some
kind of "well-known" location for such a file on the puppet-puppetboard
module side.
This is step 1 of the process described in https://github.com/voxpupuli/puppet-puppetboard/pull/329#issuecomment-886096120
=> Add a sample settings.py

.github/workflows/tests.yml, puppetboard/app.py, puppetboard/static/css/puppetboard.css, puppetboard/static/js/pretty.js, puppetboard/templates/_macros.html, puppetboard/templates/fact.html, puppetboard/templates/layout.html, puppetboard/templates/node.html, puppetboard/templates/query.html, puppetboard/utils.py, test/test_app.py, test/test_utils.py
#643 + #644
Fixes  #612 and #567 and (I think that) it implements #83.
Here's a screenshot of how will the complex facts look: https://github.com/voxpupuli/puppetboard/pull/644#issuecomment-974807389
=> Structured fact values as shown as pretty-printed, colored JSON + some bugs fixed

MANIFEST.in
Add the following files to the pypi package ：
puppetboard/static/favicon.ico
puppetboard/static/favicon.svg
puppetboard/static/fonts/Cousine-Regular.ttf
puppetboard/static/fonts/lato-italic-400.ttf
puppetboard/static/fonts/lato-italic-700.ttf
puppetboard/static/fonts/lato-normal-400.ttf
puppetboard/static/fonts/lato-normal-700.ttf
=> PyPI package adds missing fonts and icons

README.md, puppetboard/docker_settings.py, test/test_docker_settings.py
Closes https://github.com/voxpupuli/puppetboard/issues/669
Adds support for passing certificates and keys to the following environment variables:
* PUPPETDB_SSL_VERIFY
* PUPPETDB_KEY
* PUPPETDB_CERT
I have tested this in my own environment as per the issue. With the container running in AWS Fargate, certificates being passed as env vars from AWS SSM Parameter store.
I had ran into a couple edge cases where the shell was breaking the new lines. These feel like general environment variable edge cases and not so much an issue with this code.
=> Support passing puppetdb certificates via environment variables

puppetboard/docker_settings.py
Use coerce_bool function for ENABLE_QUERY environment variable
=> Fix  Query tab cannot be disabled on Docker #682

Dockerfile
In theory this should be right....
=> Run health check more cleanly and more often

puppetboard/templates/query.html, puppetboard/views/query.py, test/views/test_query.py
=> Stop modifying the query response for showing as JSON

puppetboard/static/css/puppetboard.css
From a user experience perspective, it would make sense to remove the `border-radius` which is added by `semantic.min.css` and thus make the top navigation appear more clearly anchored to the page.
=> Remove border-radius from Top Menu

README.md, puppetboard/core.py, puppetboard/default_settings.py, puppetboard/docker_settings.py, puppetboard/errors.py, puppetboard/templates/layout.html, puppetboard/utils.py
Hi,
I fixed an old issue which concerns the selection of environments. When you have many environments, display and selection are quite difficult.
I changed the location to the right of the menu and used the Semantic UI select search dropdown to make it easier to search and select.
However I had to add some javascript to do the redirection and css to fix dropdown / loading icon.
The only inconvenience of this solution is that you can no longer right click > open in new tab on an environment.
I tested this fix in the latest chrome and firefox browsers.
Example of the issue :
Results after fix :
=> Improve UI of the environment selection

README.md, puppetboard/app.py, puppetboard/default_settings.py, puppetboard/docker_settings.py, puppetboard/views/inventory.py, test/test_docker_settings.py, test/views/test_inventory.py
Hello,
I wanted to use inventory page but it only works with few linux OS. Here is my proposal to support many OS. I have introduced a new parameter named `INVENTORY_FACT_TEMPLATES` to keep customization. This parameter is used to customize cell display using jinja. Default INVENTORY_FACTS has been changed to use trusted and os facts.
It has been tested with Puppet agent >= 5 to 7:
- Windows (Pro, Server 2012/2016/2019)
- MacOS
- Debian Family (Debian, Ubunut, Linux Mint, etc.)
- Redhat Family (RedHat Enterprise, Oracle Linux, CentOS)
- Suze Family (SUZE Enterprise)
With puppet agent 4, windows os will display nothing.
It should fix #485. 
What do you think about this changes ?
=> feature: improve os detection for inventory page

requirements.txt
https://stackoverflow.com/a/73932581/2693875
=> Workaround for incompatiblity with Python 3.7 

puppetboard/templates/report.html
Hello,
With many debug messages it becomes difficult to quickly pick out any error messages on a report page. This change removes the 'error' css class from debug rows so that debug level rows are left as white. Open to alternatives. 
Thank you.
=> Removed error styling from debug lines on report

puppetboard/views/facts.py
Not sure how this ever worked - on a node page, `fact` defaults to `None` and produces this error `TypeError: 'in <string>' requires string as left operand, not NoneType`
Fixes #907
=> Check if fact is None (default for full node view)

README.md
Readd link which was dropped in 8e3811c2cf1bc5540d2e6f3b4f6b68dd72e4e2a5
=> Add link to C3.js documentation

README.md
=> README: note that `SECRET_KEY` can't be empty

README.md
- add section on SECRET_KEY
- add example for PuppetDB SSL within Puppet code
- correct parameter explanation
=> Update README for SECRET_KEY and SSL Setup

puppetboard/templates/radiator.html
I see 404 errors in nginx due to the radiator looking for `/favicon.ico` instead of my subfolder url that the rest of puppetboard looks for.
Small fix, but reduces a little bit of noise for me. 😅
=> Add favicon to radiator

.github/workflows/publish-to-pypi.yml, .github/workflows/tests.yml, README.md, setup.py
at least to the PyPI package, because the Docker image has been built using Python 3.12 since October 2023 (d05043412a1fa7f2672f2a86235b9259c9c57230) so v5.1.0
=> Add official support for Python 3.12

puppetboard/static/css/puppetboard.css
Structured facts are potentially very long, so it can be hard to find the keys and values. This puts them at the top of the cells, which might be less visibly pleasing from a design perspective, but is definitely more useful.
=> Align structured facts with tops of cells

puppetboard/static/custom-natural/natural.js, puppetboard/templates/_facts_sorter.html, puppetboard/templates/_macros.html, puppetboard/templates/fact.html, puppetboard/views/facts.py
solve issue #731
* implement natural sorting for fact=kernelrelease
* create a sorter_map with key=fact and value=sorter type, now having (kernelrelease, natural) and (uptime, natural-time-delta)
* remove natural_time_delta_sort flag
=> Sort kernelrelease fact

README.md, puppetboard-s2i-template.yaml
I have created an OpenShift template that allows very easy creation and configuration of the Puppetboard Docker image.
Neither the location nor the name of the template file is of any consequence (to me) so I'm looking to the community for guidance.
I have updated the README.me and it's a giant work in progress.  
I would appreciate comments and changes as needed.
I realize that everything is still very rough but I wanted to get the Voxpupuli community engaged.
=> Adding OpenShift Template

puppetboard/docker_settings.py
Add APPLICATION_ROOT to docker_settings.py. This way setting PUPPETBOARD_URL_PREFIX works. If APPLICATION_ROOT is not set and PUPPETBOARD_URL_PREFIX is set, every call will result in a 500 error with "IndexError: list index out of range".
This should resolve #1092
=> Add APPLICATION_ROOT to docker_settings.py
