- README.rst
> Add reference to docker image

- puppetboard/app.py
- puppetboard/templates/layout.html
> Add version and current year to the layout

- puppetboard/static/coffeescript/tables.coffee
- puppetboard/static/css/puppetboard.css
- puppetboard/static/js/tables.js
- puppetboard/templates/index.html
- puppetboard/templates/nodes.html
Hey there again,
I've added a skip count for each node on the overview page along with a reported column which is very helpful on the overview page.
Cheers
Fotis
> Further details for nodes added (skip count and reported date on overview page)

- puppetboard/app.py
- puppetboard/templates/index.html
renamed node in @app.route('/reports/<node>') to node_name
renamed node in {% if node.report_timestamp %} to node_name
> Fixed variabel names in index.html and app.py

- README.rst
I'm the new maintainer of puppetdb and puppetboard on ArchLinux
> update ArchLinux Package maintainer

- puppetboard/app.py
- puppetboard/templates/index.html
Fixes https://github.com/voxpupuli/puppetboard/issues/213
Also changing the 'if' condition from '!=' to '>' since this application
can only work with unsigned integers
> templates/index: Directly referencing config.REFRESH_RATE

- requirements.txt
An enhancement to https://github.com/voxpupuli/puppetboard/pull/158 except
not relying on a specific version.
> requirements.txt: Removing the version specific request package requirement

- puppetboard/app.py
> puppetdb 4.x metric api calls

- puppetboard/app.py
- puppetboard/forms.py
- requirements.txt
Requires https://github.com/voxpupuli/pypuppetdb/pull/97
> Add PQL endpoint to Query form

- puppetboard/app.py
- requirements.txt
- setup.py
This fixes #239 
The pypuppetdb.QueryBuilder allows for Object-Oriented building of PuppetDB queries without having to construct and maintain long, complicated strings.
Replacing all query string constructions with this new Object-Oriented approach.
> Implementing new pypuppetdb.QueryBuilder

- Dockerfile
- puppetboard/default_settings.py
- wsgi.py
This PR adds support for easily developing and deploying Puppetboard with Docker.
> Add wsgi.py and Dockerfile

- puppetboard/utils.py
> Fix whitespace

- .coveragerc
- .gitignore
- .travis.yml
- conftest.py
- dev.py
- puppetboard/app.py
- puppetboard/default_settings.py
- puppetboard/forms.py
- puppetboard/utils.py
- requirements-test.txt
- setup.cfg
- setup.py
- test/test_app.py
Added pep8 and starting python test code. Fixed pep8 formatting violations.
I also added a hook for coveralls, You will need to create a coveralls account to get coverage reports.
https://coveralls.io/builds/6850068
Fixes issue #266
> Travis ci integration

- puppetboard/app.py
Replaced oder_by_str with order_by_str in get_or_abort() to fix app crash.
> Fixed a typo in Puppetboard's catalog view

- .travis.yml
- bandit.sh
- requirements-test.txt
Bandit (https://github.com/openstack/bandit) is a python
security linter.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> [Security] Implement bandit

- README.rst
> Updating documentation for secret_key

- Dockerfile
- README.rst
- puppetboard/docker_settings.py
- requirements-docker.txt
- test/test_docker_settings.py
Update default_settings.py to behave as it exists today with it's settings, but allow for configuration to be overwritten using environment.  This allows for simpler docker deployments.
> Default settings use environment variables

- puppetboard/app.py
- puppetboard/templates/412.html
- puppetboard/templates/layout.html
- puppetboard/templates/node.html
- puppetboard/templates/radiator.html
- requirements-test.txt
- test/test_app.py
- test/test_app_error.py
- test/test_docker_settings.py
- test/test_utils.py
Working on better testing with flask.  Mocking out puppetdb some so we the initial page can load.
Updating some templates to have ending tags for better parsing.
> Flask testing.

- puppetboard/app.py
> Metrics can appear as paths, if these paths are passed

- puppetboard/templates/node.html
Fixes a regression from moving JS into head.
> Node template js fix

- puppetboard/dailychart.py
- test/test_app.py
> Fix dailychart in python3 + write a test for it

- CHANGELOG.rst
- puppetboard/templates/layout.html
- setup.py
> Prepare for release 0.2.2

- .travis.yml
- Dockerfile
- requirements-docker.txt
- requirements-test.txt
- requirements.txt
- setup.cfg
- setup.py
- tox.ini
Use pip '-r' in the requirements files and use them to create a simple requirements hierarchy.
Use the new requirements.txt and requirements-test.txt inside of setup.py to define the requirements for each of test and install dependencies.
> Simple requirements

- puppetboard/app.py
- puppetboard/forms.py
- requirements.txt
- test/test_app_error.py
- test/test_form.py
- test/test_utils.py
Update requirements to use newer versions of flask.
Flask forms, needed to be updated to use depreciated classes.
Fixing #370
> Dependency update

- puppetboard/static/css/radiator.css
- puppetboard/templates/radiator.html
Changed wording for Pending to Noop. Fixing #365
> Updating radiator CSS to match that of the main CSS.

- README.rst
- docs/Debian-Jessie.md
Adding debian jessie installation.
Updating configuration bit documentation.
Fixes #366
> Update user documentation

- requirements.txt
> Update for pypuppetdb

- README.rst
Made two changes to the README, removing old mentioning of stability issues no longer relevant, and adding note about PuppetDB compatibility.
> Update README, addressing #421 and #412

- MANIFEST.in
Adding template files that were missing to the package.
Fixing #420
> Include template files for altering Semantic css and fonts

- README.rst
> Propose small spelling change

- README.rst
An amazingly trivia PR. But also proof that someone read the docs you spent so much effort on?
> Fix a typo

- puppetboard/dailychart.py
> Query using producer_timestamp index vs. start_time

- MANIFEST.in
> Adding missing components for building source packages.

- README.md
Fixes https://github.com/voxpupuli/puppetboard/issues/486
> Update links to Puppet docs

- README.md
- tox.ini
Those are the Python versions that this project currently supports.
> Test/document python versions: 2.7,3.5,3.6,3.7

- CHANGELOG.md
- puppetboard/version.py
- requirements.txt
- setup.py
This is a quick first attempt at a 1.0.0 changelog, based on the description of commits to master since the 0.3.0 release.
I skipped changes to documentation, typo fixes and similar "non-functional" things. Please do review and comment if something's missing.
> 1.0.0 version and CHANGELOG

- puppetboard/static/js/dailychart.js
Fix for #424 by referencing base site url plus daily report location.
> Fix problem loading daily chart on node page

- Dockerfile
> fix gunicorn parameter and allow to define workers in docker

- .gitignore
- .travis.yml
- puppetboard/app.py
- puppetboard/core.py
- puppetboard/dailychart.py
- puppetboard/errors.py
- puppetboard/forms.py
- puppetboard/static/Semantic-UI-2.1.8/themes/default/assets/fonts/icons.svg
- puppetboard/utils.py
- pytest.ini
- requirements-test.txt
- requirements.txt
- setup.cfg
- test/test_app_error.py
- test/test_docker_settings.py
- test/test_form.py
- test/test_utils.py
- tox.ini
Cleanup of unused code, getting rid of star import from pypuppetdb and replacing imported libraries with local imports.
Added mypy to tests.
CommonMark bumped to 0.9.1, since #497  was merged.
> Adding mypy + Cleanup + CommonMark upgrade to 0.9.1

- puppetboard/forms.py
- puppetboard/templates/query.html
Use a select field to choose API endpoint in query, default to PQL.
> Use a select for endpoint selection in query

- puppetboard/templates/_macros.html
edit: this adds a Noop label in the Overview *and* the Nodes view
> overview: add noop column

- puppetboard/templates/_macros.html
> add title to events labels in overview and nodes

- puppetboard/templates/_macros.html
Fixes a CSS mistake introduced in #584
> Fix noop class in _macros.html

- puppetboard/utils.py
- test/test_utils.py
Log any other exception that can be raised from execution of a function and raised 500
> Manage any other exception for get_or_abort

- puppetboard/templates/_macros.html
> changing the default sort order for facts_table

- puppetboard/templates/reports.html
On the reports view, allow to toggle reports by clicking the label of the checkboxes.
> Allow to toggle checkboxes by clicking their label

- puppetboard/version.py
- requirements.txt
We have been testing 3.1.0 RC1 for about a month without finding any issues. Also no issues have been reported by other users in GitHub.
Therefore I think that we can release a final 3.1.0.
> Release 3.1.0 (final)

- .github/workflows/publish-docker.yml
- .github/workflows/publish-to-pypi.yml
to the GitHub Container Registry (ghcr.io)
> Release a Docker image with GHA

- puppetboard/app.py
- puppetboard/templates/layout.html
Use function to resolve menu entries, which are enabled
This should resolve issue #627
> Remove menu entry if feature is disabled

- .github/workflows/tests.yml
- requirements-test.txt
- test/test_app.py
and make the tests run in random order from now on.
Thanks to shenganzhang for reporting the issue!
Fixes #646
> Fix test failures shown by introducing random order

- puppetboard/templates/query.html
This is a PR with the code in #655
> Make the query shareable using URL

- Dockerfile
This small update aims to allow configuration of bind host on Docker.
> Configurable Binding host in Dockerfile

- puppetboard/templates/query.html
- puppetboard/views/query.py
> Fix: handling facts in queries 

- setup.py
> remove unused import in setup.py

- Dockerfile
This is related to #687 and adds a fairly minimal not that exciting health check.
> Minimal builtin health check

- puppetboard/templates/index.html
- puppetboard/templates/node.html
- puppetboard/templates/nodes.html
- puppetboard/templates/report.html
Remove unwanted changes from #708 :
- Regression for nodes order on index page 
@gdubicki I have missed some localized timestamp fields. I have add them to this PR
> Fix frontend dependencies

- .github/workflows/tests.yml
- .gitignore
- README.md
- puppetboard/app.py
- puppetboard/templates/failures.html
- puppetboard/templates/index.html
- puppetboard/templates/node.html
- puppetboard/templates/nodes.html
- puppetboard/templates/report.html
- puppetboard/templates/reports.json.tpl
- puppetboard/views/index.py
- puppetboard/views/query.py
- requirements-test.txt
- setup.cfg
- wsgi.py
Fixes https://github.com/voxpupuli/puppetboard/issues/461
Plus various fixes for running tests.
> Fix LOCALISE_TIMESTAMP=False and document better how LOCALISE_TIMESTAMP works

- puppetboard/templates/radiator.html
> fix offline mode jquery path

- puppetboard/views/classes.py
> fix: Fixed broken links in Class view

- CHANGELOG.md
- README.md
- RELEASE.md
- puppetboard/version.py
- trigger docker hub build
- add release documentation
> Release 5.2.0

- .github/dependabot.yml
i hope/think that it will be easier to merge them with groups
> try to group dependabot updates together

- Dockerfile
inspired by https://github.com/gitlabform/gitlabform/pull/719 by @lkwg82 (thanks!)
> Don't run app as root in Docker container

- CHANGELOG.md
- puppetboard/version.py
New release request, replaces #1199
> Release 6.0.0

- RELEASE.md
- puppetboard/version.py
Also update the RELEASE documentation to note that
> Make pyproject.toml the source of version

- CHANGELOG.md
- Rakefile
- pyproject.toml
- run pipeline again to publish
- switch version detection in changelog to branch name
> Release 6.0.1
